[theme]
base = "light"

# General color setup
textColor = "#1f2937"
primaryColor = "#16a34a"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f3f4f6"

# Widgets
showWidgetBorder = true
borderColor = "#d1d5db"

# Dataframes
dataframeHeaderBackgroundColor = "#e5e7eb"

# Heading text
headingFont = "Space Grotesk"
headingFontWeights = [700, 600, 500, 500, 400, 400]
headingFontSizes = ["3rem", "2rem", "1.4rem"]
